### ISSUE TITLE
Universally failing tests

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1058]
This category of test fails on all builds.  These generally correspond to bugs in QMCPACK and each item in the checklist below should have a corresponding GitHub bug issue to track the specific developments leading to a fix.

- [ ] AFQMC NiO fails (issue: , fix: )
- [ ] AFQMC with nnodes=2 fails (issue: #1040, fix: )
- [ ] NiO performance runs with 512 atoms fail (issue: , fix: )
- [ ] RPA Jastrow is broken (issue: #848, fix: )
- [ ] Orbital optimization is incompatible with DMC (issue: , fix: )
- [ ] Spin density estimator is incompatible with open BC's (issue: #998 , fix: )
- [ ] Densities have incorrect weight in DMC (issue: #934, fix: )
- [ ] Density estimator test is incompatible with no mpi (issue: #997, fix: )
- [ ] 1RDM estimator is incompatible with threading (issue: #995, fix: )
- [ ] 1RDM values are incorrect **(new breakage)** (issue: #1052, fix: )
- [ ] Energy density is broken due to bug in Traces (issue: #982, fix: )
- [ ] Nexus example tests fail due to file writing problem (issue: #1028, fix: )

See #1062 for an overarching view of the testing problem and links to its other aspects.

**Comment by prckent** [comment]
Is this list still current? Some look done, but there may be residual problems.

(512 atom NiO probably broke due to lack of memory. Ye has been running an equivalent by hand, however we don't have a large memory machine reporting to cdash yet.)

**Comment by ye-luo** [comment]
512 atom problem with 16 walkers needs only 32 GB memory. Probably due to time out.

**Comment by jtkrogel** [comment]
Outdated.
