### ISSUE TITLE
CUDA incompatibility

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1059]
The current CUDA code is not compatible with many features in the main code.  While some of these incompatibilities will never be resolved due to choice, this issue documents those features that are intended to work on the GPU, but do not.  Similar in spirit to #861.  Also covers unstable tests that fall in this category.

Features/tests desired to work on GPU, but that currently fail:
- [ ] density estimator (issue: #925, fix: )
- [ ] spin density estimator (issue: #925, fix: )
- [ ] momentum distribution estimator (issue: #467, fix: )

See the respective issue listed for each action item for tests that must pass to consider the issue resolved.

See #1062 for an overarching view of the testing problem and links to its other aspects.

**Comment by jtkrogel** [comment]
Note: more items need to be added to the above once categorization of the GPU-side unstable tests is complete.  See #1055.

**Comment by prckent** [comment]
These missing CUDA capabilities will never be implemented by the main developers, so I am closing the issue. Anyone needing these is welcome to make the updates themselves. The plan is to delete the legacy CUDA implementation, delete the legacy AoS CPU implementation, and concentrate on adding GPU capabilities to the "SoA" CPU code in a fully compatible manner. Moving forward QMCPACK will not have internal forks and sparse feature coverage such as this.
