### ISSUE TITLE
Complete list of tests needed

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1061]
Many tests have been added, but there still remain many features that need to have tests added.  The list below is meant to capture all features that do not yet have a test, or known breakages that do not yet have a corresponding test so that corresponding fixes can be pursued and validated.

Real space estimator tests needed:
- [ ] Chiesa kinetic energy correction (PR: , see also #1003 )
- [ ] MPC potential energy correction (PR: , see also #1002 )
- [ ] momentum distribution (PR: , see also #627 )
- [ ] pair correlation function (PR: , see also #396 )
- [ ] structure factor--SkEstimator (PR: , see also #1000 )
- [ ] structure factor--StaticStructureFactor estimator, spin resolved (PR: , see also #999 )
- [ ] structure factor--SkAllEstimator, finite size corrections (PR: , see also #1001 )
- [ ] energy density matrix (PR: , see also #981, #983 )
- [ ] traces (PR: )
- [ ] forward walking (PR: , see also #1004 )
- [ ] core polarization potential (PR: , see also #1005 )
- [ ] force estimators in open BC's (PR: , see also #332 )
- [ ] force estimators in periodic BC's (PR: , see also #332 )

Real space wavefunction tests needed:
- [ ] excited states in Slater determinant (PR: , see also #740 )
- [ ] matrix tiling of B-spline orbitals (PR: , see also #575 )
- [ ] quasi-2D boundary conditions (?) (PR: , see also #578 )

Real space method tests needed:
- [ ] pade2 Jastrow optimization (PR: , see also #412)
- [ ] orbital optimization with Bspline orbitals (PR: , see also #637, #638)
- [ ] orbital optimization demonstrating incorrect energy with LCAO (PR: , see also #638)
- [ ] CSVMC with openmp enabled (PR: , see also #362)
- [ ] RMC test demonstrating BlockWeight problem (PR: , see also #180)
- [ ] DMC test demonstrating stochastic reconfiguration problem (PR: , see also #18 )
- [ ] DMC restart test (PR: , see also #798 )
- [ ] DMC size consistent T-moves with splines (PR: , see also #630 )

Real space deterministic tests needed:
(plan out first set of tests to add here, see also #704 )

Auxiliary field estimator tests needed:

Auxiliary field method tests needed:

**Comment by jtkrogel** [comment]
@rcclay are there other RMC features that aren't covered yet?

@mmorale3 should this be filled out now, or following the mainline merge of your updated AFQMC?

**Comment by rcclay** [comment]
@jtkrogel Not that I can think of off the top of my head.

**Comment by Hyeondeok-Shin** [comment]
I'm now working with the real space wavefunction tests (including deterministic test), but please let me know if someone is already working with a certain test in order to avoid conflict.

**Comment by jtkrogel** [comment]
@Hyeondeok-Shin You mean via the wavefunction tester?  I expect pass/fail criteria for the finite differences will require some tinkering.  If this is the case, perhaps make a new issue for further discussion on that topic.

Please can you add the deterministic integration tests you will be working on next to the header comment under the appropriate section?

**Comment by Hyeondeok-Shin** [comment]
@jtkrogel I see. I'll be adding the deterministic integration tests list I'm (will be) working on.

**Comment by prckent** [comment]
Please steer clear of the "wavefunction tester" for new tests. It is another layer of indirection and uncertainty to investigate when something goes wrong.

A test of traces would be preferred by far, be simpler, and achieve the same coverage.

**Comment by prckent** [comment]
Renamed for clarity.

**Comment by walshmm** [comment]
Was wondering how up to date this issue is. Wanted to look at where I could start writing tests, though I dont want to step on anyone's toes as I understand some parts of the code are being refactored.

**Comment by prckent** [comment]
It is fairly up to date. Since this indexing issue was created we have added use of codecov, which also is a good guide to where tests might be missing. Of course the reported codecov coverage https://app.codecov.io/gh/QMCPACK/qmcpack only sees the tests run in CI, not our complete set of tests, so the coverage is somewhat better.

Many of these require either wholly new input files to use the functionality or they require a bit of infrastructure. e.g. https://github.com/QMCPACK/qmcpack/issues/1103  is important to test, but new cmake macros would be needed to copy multiple input files, run "qmcpack listofinputs.txt", and then analyze the results. The individual runs can be repeats of runs where we have existing tests.

**Comment by prckent** [comment]
Since we can only have 3 pinned issues but some of this issue is still relevant I am going to link to #3508 which is more relevant to current priorities and the upcoming release.
