### ISSUE TITLE
Taming the testing system

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1062]
This is the overarching issue addressed by several sub-issues, many of them carrying the label "unstable".  Ultimate resolution of this issue is a complete, passing test system and feature completeness to the extent desired of major internal branches of QMCPACK.

The two main tasks related to determining the scope of the testing problem and providing a route to its resolution are:
- [ ] Making a complete list of tests needed and implementing them (see #1061 )
- [ ] Categorizing known failing tests and revamping CDash to reflect known passing tests (see #1055)

Issues have been created for test categories to track progress toward making the testing system fully functional and to resolving incompatibilities between major modes of QMCPACK.

Test categories relating to making the testing system fully functional as well as identifying bugs are (in addition to #1061 ): 
- [ ] Universally failing tests (see #1058 )
- [ ] Intermittently failing tests (see #1057 )

Test categories relating to incompatibilities between major modes of QMCPACK are:
- [ ] Real vs. complex incompatibility (see #1056)
- [ ] CUDA incompatibility (see #1059)
- [ ] SoA incompatibility (see #861 )

Another important change is to update tests to catch threading incompatibility:
- [ ] Add tests with threading enabled (see #988 )

**Comment by jtkrogel** [comment]
Outdated.
