### ISSUE TITLE
Spin-Orbit Commit Plan

### ISSUE THREAD

**Issue by rcclay** [QMCPACK/qmcpack#1770]
Hi all!  Here's my tentative PR schedule for getting spin-orbit estimators and spin DMC into QMCPACK:

- [x] Establish an XML format for QMCPACK PP's with SO interactions.  Have this format be parsed and "registered" by QMCPACK, meaning that skeleton classes are constructed where they should be and data ends up where it should.  (PR #1771 )
- [x] Augment the LCAO h5 and/or pwscf.h5 file formats to handle spinors. Parse these and check that data is ending up in correct skeleton classes. (PR #2104)
- [x] Implement spinor orbital class and SpinorSlaterDeterminant classes. (PR #2104).
- [x] Implement SO potential evaluation. (PR #2312, #2325)
- [x] Implement SOVMC and SODMC. (PR #2147, #2197)

**Comment by prckent** [comment]
Please try to write tests as you go so that (as much as possible) the different components can be tested independently.

**Comment by ye-luo** [comment]
@rcclay done? close?

**Comment by rcclay** [comment]
Implementation is done.  We're tracking a bug in PBC's, but that should be a separate issue.
