### ISSUE TITLE
Work plan to transition evaluate_sp to SoA

### ISSUE THREAD

**Issue by jtkrogel** [QMCPACK/qmcpack#1866]
Related to #861 and #1796.  Perform transition to SoA for all evaluate_sp functions used by energy density estimator.  Take the simpler strategy of temporarily enabling the functions without full reactivation of energy density, write deterministic AoS output, implement SoA, and verify SoA gives the same deterministic output.

This will be done for the following classes:
- [x] CoulombPBCAA (via diamond)
- [x] CoulombPBCAB (via diamond)
- [x] CoulombPotential (via LiH)
- [x] LocalECPotential (via LiH)
- [x] NonlocalECPComponent (via LiH)

When EnergyDensity is later reactivated, additionally SpaceGrid will need to be updated for Voronoi grids.

**Comment by prckent** [comment]
@jtkrogel OK to close this issue?

**Comment by jtkrogel** [comment]
Yes.
