### ISSUE TITLE
Commit plan for batched spin-orbit code

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#3712]
**Is your feature request related to a problem? Please describe.**
Below is a checklist to help me keep track of what is done for the SO capability in the batched code. This helps close #3508 

**Describe the solution you'd like**

- [x] add spin moves in multiwalker APIs (#3710, #3728)
- [x] add spin gradients (e.g. evalGradWithSpin APIs) to TWF and TWFdispatcher for mw evaluation (#3714, #3887)
- [x] add spin gradients (e.g. evalGradWithSpin APIs) to  DiracDeterminant for mw evaluation (#3887, #4182, #4208, #4269 )
- [x] add mw evaluation to SpinorSet (#3726, #3730, #4208, #4226, #4231)
- [x] update VMC/DMC batched drivers to include spin moves (#3774, #3762, #3867)
- [x] update SOECPComponent and SOECPotential to include mw evaluations(#4375, #4504)

**Describe alternatives you've considered**

**Additional context**

**Comment by prckent** [comment]
Please can you update the status? What remains?

**Comment by camelto2** [comment]
In terms of running calculations, everything is technically there for single determinants and users should be able to run. The only caveat is that for SOECPotential, they fall back to single walker APIs from the definition in operator base. I'm working on the actual mw_ APIs for SOECPotential now, which should be finished shortly. After that, the only missing piece is MSD

**Comment by camelto2** [comment]
closing this and moving the mw_ APIs needed for MSD to its own issue. Batched Spin-Orbit is finished for our standard workflow with single slater jastrow wave functions
