### ISSUE TITLE
Multidetrminant offload plan

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#3830]
- [x] Part 1: All heavy kernels were executed on the GPU. Said Kernels were in batched function but data was generated on host and transferred back and forth too many times between host and accelerator. by #2926 

- [ ] Part 2: All data needed for heavy kernels is now generated in batched code. #3807

- [ ] Part 3: All data needed for heavy kernels is generated on the GPU from the batched code. #3827
