### ISSUE TITLE
LCAO offload todo list

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#4615]
LCAO offload.
- [ ] make mw/GEMM versions of evaluateValue and DetRatios
- [ ] offload mw_evaluateVGL and mw_evaluateVGLandDetRatioGrads
- [ ] offload mw_evaluateValue and mw_evaluateDetRatios
- [ ] offload AO evaluation (either before or after reworking AO eval algorithm)
