### ISSUE TITLE
Spline orbital optimization tracker

### ISSUE THREAD

**Issue by camelto2** [QMCPACK/qmcpack#4865]
Issue to track all the variations of splines and whether or not they support orbital rotation

**Normal Splines**
- [x] SplineR2R (#3907, #4710)
- [ ] SplineC2R
- [x] SplineC2C (#4505, #4710)
- [ ] ~~SplineC2ROMPTarget~~ no longer in code base.
- [ ] ~~SplineC2COMPTarget (almost ready, see [splc2comp_applyRotation](https://github.com/camelto2/qmcpack/tree/splc2comp_applyRotation))~~ no longer in code base.

**Hybrid Representation**
- [x] Hybrid SplineR2R (#4862)
- [ ] Hybrid SplineC2R
- [x] Hybrid SplineC2C (#4862)
- [ ] ~~Hybrid SplineC2ROMPTarget~~ no longer in code base.
- [ ] ~~Hybrid SplineC2COMPTarget~~ no longer in code base.

**Comment by jptowns** [comment]
I have an idea: Let's get rid of C2R entirely. It's an edge case. And, while I don't know for certain, i suspect it is very rarely used in production. Perhaps we can try deprecating it and see if anyone complains. If, in 6 months, say, no one has noticed we can just remove entirely. Thoughts @ye-luo ? @prckent ?

**Comment by prckent** [comment]
This is a good suggestion.  The question I have is how often the c2r path is used in practice (vs in theory )?

**Comment by prckent** [comment]
What is the current situation here? Are the unimplemented cases fully error trapped?

**Comment by ye-luo** [comment]
> Are the unimplemented cases fully error trapped?
~~Yes.~~ Actually we don't have proper trap.
```
  if (isRotationSupported())
    throw std::logic_error("Bug!! " + getClassName() +
                           "::applyRotation "
                           "must be overloaded when the SPOSet supports rotation.");
```
~~only supported implementation hits true case, it is false by default.~~
The above trap serves a different purpose. I just added a trap for developers https://github.com/QMCPACK/qmcpack/pull/6205

**Comment by ye-luo** [comment]
At the builder level, there is trap for user.
```
    if (!sposet_ref.isRotationSupported())
      myComm->barrier_and_abort("Orbital rotation not supported with '" + sposet_ref.getName() + "' of type '" +
                                sposet_ref.getClassName() + "'.");
```
