### ISSUE TITLE
Remaining tasks for AoS to SoA transition

### ISSUE THREAD

**Issue by ye-luo** [QMCPACK/qmcpack#861]
This is the final list of tasks that have priority before the remaining AoS code is fully removed from the source.  The AoS removal likely will occur sometime in Oct. 2019.  Even code listed as "priority" below will be removed once the deadline is exceeded if the assignee(s) have not ported by then and this issue will be closed.

All remaining AoS code has been encapsulated by if-defs.  The changes made in the following PR highlight all remaining AoS code:

https://github.com/QMCPACK/qmcpack/pull/1846/files

Priority code to port before the Oct. deadline:
- [x] g(r) (issue: #1699, assignee: @markdewing, PR: #2035)
- [x] Chiesa/Ceperley and bare force estimators (issue: #1795, assignee: , PR: )
- [x] energy density and energy density matrix estimators for EKT (issue: #1796, assignee: @jtkrogel, PR: #1869)
- [x] orbital optimization (issue: , assignee: @spinedaflores , PR: #1893)
- [x]  lattice deviation estimator (issue: , assignee: @Paul-St-Young, PR: #1938)
- [x] "Chiesa" S(k) kinetic energy correction (issue: #2025, assignee: @Hyeondeok-Shin @ye-luo, PR: #2050).
- [x] NLPP derivatives in optimization (issue: #2083, assignee: @ye-luo, PR #2179)

Code that is slated for deletion after the Oct. deadline (volunteers welcome!):
* complex HEG backflow (see #1227)
* spin-dependent electron-ion backflow
* AoS cusp correction code ~~(SoA code has problems, see #1388)~~
* FDLR wavefunction
* numerical orbitals
* stress estimator (see #970) 
* core polarization potential

Note: tests that pass for AoS but fail for SoA:
* long-diamondC_1x1x1_pp-vmc_sdj-1-16-flux (wavefunction error!)
* short-c_no-hf_vmc-1-16 (numerical orbitals)
* long-c_no-hf_vmc-1-16
* short-c_no-sj_dmc-1-16
* long-c_no-sj_dmc-1-16
* short-H2-FDLR-16-1 (FDLR wavefunction)
* short-H2-orb-opt-16-1 (orbital optimization)
* short-H4-orb-opt-dmc-1-16

**Comment by PDoakORNL** [comment]
What about the optimizable wave function support?

I'm working on the CUDA code now.  
I've begun JastrowCUDAClass switch to the OrbitalBase base class.

**Comment by ye-luo** [comment]
`JastrowCUDAClass switch to the OrbitalBase base class` what is this?
Currently, the code does
```
class OneBodyJastrowOrbitalBspline :
  public OneBodyJastrowOrbital<BsplineFunctor<OrbitalBase::RealType> >
```
OneBodyJastrowOrbital needs to be replaced with J1OrbitalSoA.

Jastrow optimization is supported with CUDA build.

**Comment by PDoakORNL** [comment]
The optimization I was talking about was of the single particle orbitals.

At the moment I have a J1OrbitalCUDASoA so as to look at what can be shared and what can't. 
Not sure if it will be
J1OrbitalCUDASoA : public J1OrbitalSoA and eventually J1OrbitalCUDA : public J1Orbital
or
J1OrbitalCUDA : public J1OrbitalBase
J1OrbitalCPU : public J1OrbitalBase

So that we end up with a call like this:
```C++
return createOneBodyJastrow<J1OrbitalCUDASoA<RadFuncType>,DiffOneBodySpinJastrowOrbital<RadFuncType> >(cur);
```
A certain amount of the old CUDA OneBody and TwoBody code will go in but my current strategy is to make sure that any feature we don't have in CUDA we are following the SoA "method" and can degrade to the CPU implementation.

Although this is speculative at the moment since I'm still working in the determinant code.

**Comment by prckent** [comment]
Quick comment on the CUDA-> SoA transition, agreeing with @ye-luo 's list at the top: happily the CUDA SoA build is working for solids apart from runs involving Jastrows. e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=2572921&build=24790 shows that DMC is working with single determinant no Jastrow. After that the gaps are things like J3 and the new hybrid rep.

**Comment by PDoakORNL** [comment]
RPAJastro is dependent on TwoBodyJastroOrbital.  It also looks a bit unfinished in general.

**Comment by jtkrogel** [comment]
@ye-luo, please add this to the checklist at the top: "evaluateHessian for J1 and J2".  These are present in AoS, but not SoA and I am using them in research now.

**Comment by jtkrogel** [comment]
@ye-luo please also add the evaluate_sp functions that appear in a number of QMCHamiltonianBase.  These functions are needed to obtain and transmit single particle energies that are used by Traces, energy density, and energy density matrix.

**Comment by jtkrogel** [comment]
Please also add Stress, see #970.

**Comment by prckent** [comment]
Note: We intend to flip the default to SOA shortly, since nearly all common features are implemented and we have observed that some users are overlooking the performance benefits of the SOA code. If anything critical is missing, please update this issue and the checklist at the top.

**Comment by prckent** [comment]
Update: SoA is now the default, but this issue remains relevant: at some point the AoS code will simply be deleted along with the legacy CUDA code. This will restore QMCPACK to having a single implementation "fork". To access functionality not ported will then require running an old version of QMCPACK or first porting the functionality to the current version.

**Comment by jtkrogel** [comment]
@spinedaflores Please can you comment here about your timeline for porting the orbital optimization code over?

@Paul-St-Young Is the lattice deviation estimator important to you?  If so, can you do the port to SoA?

**Comment by spinedaflores** [comment]
I'll aim to have my pull request ready by next Friday, but hopefully will have it done before then.

**Comment by jtkrogel** [comment]
@spinedaflores Thanks.  You are definitely on track to beat the rest of us.

**Comment by Paul-St-Young** [comment]
@jtkrogel yes, I would like to keep the lattice deviation estimator working. I will look into porting

**Comment by prckent** [comment]
Chiesa/Ceperley and bare force estimators are currently marked as done, but #2025 indicates they are not. Should we consider this task done or not?

**Comment by jtkrogel** [comment]
Marked as done following discussion with @tiihonej.  @tiihonej and/or @rcclay should comment here.

**Comment by tiihonej** [comment]
@jtkrogel Yes, Chiesa/Ceperley and bare force estimators have been ported to SoA. @prckent, I thought #2025 refers to a different estimator with whose details I'm not familiar.

**Comment by prckent** [comment]
Calculation of pp derivatives needs to be captured above. It is a critical capability.

**Comment by jtkrogel** [comment]
@prckent Issues have been added/updated.

**Comment by prckent** [comment]
All the items on the task list are now completed. #2179 was the last item. Following the v3.9.0 release, removal of the AoS code will commence.

**Comment by jtkrogel** [comment]
Basically done?

**Comment by prckent** [comment]
Agreed. AoS is no longer a build option.
